#!/usr/env/bin bash

set -e

# Install system build dependencies and basics
apt-get update -y &&
apt-get upgrade -y &&
apt-get install -y build-essential &&
apt-get install -y git wget curl nano redis-server nginx software-properties-common python-software-properties rustc cargo &&

# Install latest nodejs
curl -sL https://deb.nodesource.com/setup_9.x | bash - &&
apt-get install -y nodejs &&

#Install latest golang on Ubuntu
add-apt-repository -y ppa:longsleep/golang-backports &&
apt-get update -y &&
apt-get install -y golang-go &&

# Setup go path
export GOPATH=$HOME/go &&
# ??
# ln -s /.ethereum-classic/ $HOME/

#Download GETH Source
cd $HOME/ &&
go get -v github.com/ethereumproject/go-ethereum/... &&

#Download sputnikvm build files
cd $HOME/go/src/github.com/ethereumproject/ &&
git clone https://github.com/ethereumproject/sputnikvm-ffi &&
cd sputnikvm-ffi/c/ffi &&

#Build sputnikvm
cargo build --release &&
cp $HOME/go/src/github.com/ethereumproject/sputnikvm-ffi/c/ffi/target/release/libsputnikvm_ffi.a $HOME/go/src/github.com/ethereumproject/sputnikvm-ffi/c/libsputnikvm.a &&

#Build geth with sputnikvm
cd $HOME/go/src/github.com/ethereumproject/go-ethereum/cmd/geth &&
CGO_LDFLAGS="$HOME/go/src/github.com/ethereumproject/sputnikvm-ffi/c/libsputnikvm.a -ldl" go build -tags=sputnikvm . &&

#copy geth runtime to bin folder
cp geth /usr/local/bin/ &&

#download and build PM2 and etc-net-intelligence
cd $HOME &&
git clone https://github.com/Machete3000/etc-net-intelligence-api etc-net-intelligence-api &&
cd etc-net-intelligence-api &&
git pull &&
npm install &&
npm install pm2 -g &&

#clean up
rm -rf $HOME/go

